namespace PopLib.Particles;

public sealed class ParticlesEmitter()
{
	public const int DefaultImageCol = 0;
	public const int DefaultImageRow = 0;
	public const int DefaultImageFrames = 1;
	public const int DefaultAnimated = 0;
	public const ParticlesEmitterType DefaultEmitterType = ParticlesEmitterType.Box;

	public int ImageCol = DefaultImageCol;
	public int ImageRow = DefaultImageRow;
	public int ImageFrames = DefaultImageFrames;
	public int Animated = DefaultAnimated;
	public bool RandomLaunchSpin;
	public bool AlignLaunchSpin;
	public bool SystemLoops;
	public bool ParticleLoops;
	public bool ParticlesDontFollow;
	public bool RandomStartTime;
	public bool DieIfOverloaded;
	public bool Additive;
	public bool FullScreen;
	public bool HardwareOnly;
	public ParticlesEmitterType EmitterType = DefaultEmitterType;
	public ParticlesField[]? Fields = null;
	public ParticlesField[]? SystemFields = null;
	public string? Image;
	public string? Name;
	public ParticlesFloatParameterTrack? SystemDuration = null;
	public ParticlesFloatParameterTrack? CrossFadeDuration = null;
	public ParticlesFloatParameterTrack? SpawnRate = null;
	public ParticlesFloatParameterTrack? SpawnMinActive = null;
	public ParticlesFloatParameterTrack? SpawnMaxActive = null;
	public ParticlesFloatParameterTrack? SpawnMaxLaunched = null;
	public ParticlesFloatParameterTrack? EmitterRadius = null;
	public ParticlesFloatParameterTrack? EmitterOffsetX = null;
	public ParticlesFloatParameterTrack? EmitterOffsetY = null;
	public ParticlesFloatParameterTrack? EmitterBoxX = null;
	public ParticlesFloatParameterTrack? EmitterBoxY = null;
	public ParticlesFloatParameterTrack? EmitterSkewX = null;
	public ParticlesFloatParameterTrack? EmitterSkewY = null;
	public ParticlesFloatParameterTrack? ParticleDuration = null;
	public ParticlesFloatParameterTrack? SystemAlpha = null;
	public ParticlesFloatParameterTrack? LaunchSpeed = null;
	public ParticlesFloatParameterTrack? LaunchAngle = null;
	public ParticlesFloatParameterTrack? ParticleRed = null;
	public ParticlesFloatParameterTrack? ParticleGreen = null;
	public ParticlesFloatParameterTrack? ParticleBlue = null;
	public ParticlesFloatParameterTrack? ParticleAlpha = null;
	public ParticlesFloatParameterTrack? ParticleBrightness = null;
	public ParticlesFloatParameterTrack? ParticleSpinAngle = null;
	public ParticlesFloatParameterTrack? ParticleSpinSpeed = null;
	public ParticlesFloatParameterTrack? ParticleScale = null;
	public ParticlesFloatParameterTrack? ParticleStretch = null;
	public ParticlesFloatParameterTrack? CollisionReflect = null;
	public ParticlesFloatParameterTrack? CollisionSpin = null;
	public ParticlesFloatParameterTrack? ClipTop = null;
	public ParticlesFloatParameterTrack? ClipBottom = null;
	public ParticlesFloatParameterTrack? ClipLeft = null;
	public ParticlesFloatParameterTrack? ClipRight = null;
	public ParticlesFloatParameterTrack? AnimationRate = null;
}
